### ISSUE TITLE
DEVELOP AN AGENDA

### ISSUE THREAD

**Issue by sbenthall** [glass-bead-labs/symposium#2]
I would like to play a move.
I propose, no, **demand**, that we develop an agenda for the symposium.

**Comment by davclark** [comment]
Just saw this! Currently, I have way too many github events flying my way. I'm not sure how professional developers manage the different buckets of their life. It's like email, but worse.

For now, email along with such issues is a good thing.

Question - are you comfortable opening up this repo to the public (read access)? I propose to start roughing out the public-facing side that would be suitable for viewing by academic colleagues, etc.

**Comment by sbenthall** [comment]
OK, sure, why not.
